# Generated by Django 3.2.12 on 2022-05-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmessage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Failed'), (2, 'Pending'), (1, 'Sent'), (4, 'Bounce'), (5, 'Complaint'), (6, 'Delivery'), (7, 'Send'), (8, 'Reject'), (9, 'Open'), (10, 'Click'), (11, 'Rendering Failure'), (12, 'Delivery Delay'), (13, 'Subscription')], default=2, verbose_name='status'),
        ),
    ]
